//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfPoc.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class EfPocEntities : EfPoc.Infra.AtlasDbContext<EfPocEntities>
    {
        //Venkat: Custom change include deriving from AtlasDbContext instead from DbContext and having overload constructor which takes DatabaseAccessRequest
        public EfPocEntities(EfPoc.Infra.DatabaseAccessRequest request)
            : base(request)
        {
            //Disable initializer
            Database.SetInitializer<EfPocEntities>(null);
        }

        public EfPocEntities()
            : base("name=EfPocEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Span> Spans { get; set; }
    }
}
