//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfPoc.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Spans = new HashSet<Span>();
        }
    
        public long Id { get; set; }
        public string HIC { get; set; }
        public string PlanID { get; set; }
        public string PBP { get; set; }
        public string SegmentID { get; set; }
        public Nullable<System.DateTime> CurrentEffDate { get; set; }
        public string EnrollSource { get; set; }
        public string ProgramSource { get; set; }
        public string MemberStatus { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Span> Spans { get; set; }
    }
}
