//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfPoc.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Span
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public string SpanType { get; set; }
        public string SpanValue { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
